---
title: "Lab-04-personality-green-reputation"
author: "Priya Singh Collins"
date: "2/10/2022"
output: html_document
---

```{r setup}
library(tidyverse)
library(dplyr)
```

```{r}
dictionary <- readr::read_csv(here::here("data", "green_dictionary.csv"))
green_data <- readr::read_csv(here::here("data", "green_data.csv"))
```

# Exercise 1
```{r}
green_data |>
  pull(open10) |>
  unique()

green_data |>
  select(-id) |>
  unlist() |>
  unique()

# \(x) means a function "\" of x, this syntax is how to make the function, and x is the argument of the function, then after the parentheses, you write what you want the function to do.
green_data <- green_data |>
  mutate(
    across(
      -id,
      \(x) recode(x, "1" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5,
                  "-99" = NA_real_)
    )
  )

green_data
```

# Exercise 2
```{r}
# using select() gives the data frame still in the frame, but using pull() gives the data in vector form instead.

reversed <- dictionary |>
  filter(Keying == -1) |>
  pull(Item)

# one way: green2 = recode(green2, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1),
# another way:  comp6 = 6 - comp6
# another way: comp6 = max(comp6, na.rm = TRUE) - min(comp6, na.rm = TRUE) - comp6,

green_data <- green_data |>
  mutate(
    across(
      all_of(reversed),
      \(x) recode(x, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1)
    )
  )

green_data <- green_data |>
  rowwise() |>
  mutate(
    green_total = mean(c_across(green1:green5), na.rm = TRUE),
    comp_total = mean(c_across(comp1:comp10), na.rm = TRUE),
    intel_total = mean(c_across(intel1:intel10), na.rm = TRUE),
    open_total = mean(c_across(open1:open10), na.rm = TRUE),
    .after = id
  ) |>
  ungroup()

green_data

```

# Exercise 3
```{r}
green_data <- green_data |>
  mutate(
    across(
      green_total:open_total,
      \(x) 100* (x - 1) / (5 - 1),
      .names = "{.col}_pomp"
    ),
    .after = open_total
  )

green_data

```

# Exercise 4
```{r}
# using a histogram
ggplot(green_data) +
  aes(x = green_total_pomp) +
  geom_histogram()

ggplot(green_data) +
  aes(x = comp_total_pomp) +
  geom_histogram()

ggplot(green_data) +
  aes(x = intel_total_pomp) +
  geom_histogram()

ggplot(green_data) +
  aes(x = open_total_pomp) +
  geom_histogram()


```

# Exercise 5 
```{r}
green_data <- green_data |>
  drop_na(student)

ggplot(green_data) +
  aes(x = open_total_pomp, y = green_total_pomp, color = factor(student)) +
  geom_point() +
  geom_smooth(method = lm)

```

# Exercise 6
```{r}
# drops all NA's in a specific column
# green_data |>
#  drop_na(student)

# filters rows where student is not NA

green_data <- green_data |>
  mutate(green_data, student = factor(student, levels = c("1", "2"), labels = c("no", "yes")))

green_data |>
  filter(!is.na(student)) |>
ggplot() +
  aes(x = green_total_pomp, y = student, color = student, fill = student) +
  geom_jitter(height = .15) +
  geom_boxplot(color = "black",
               alpha = .5,
               width = .1,
               size = .5) +
  ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .5,
                    position = position_nudge(y = .2))


```

# Exercise 7
```{r}
green_data |>
  group_by(student) |>
  summarize(mean = mean(green_total_pomp:open_total_pomp),
            sd = sd(green_total_pomp:open_total_pomp),
            median = median(green_total_pomp:open_total_pomp),
            min = min(green_total_pomp:open_total_pomp),
            max = max(green_total_pomp:open_total_pomp))

```