---
title: "Lab 02 - Plastic waste"
author: "Priya Singh Collins"
date: "1/27/2022"
output: html_document
---

## Load packages and data

```{r setup, message=FALSE}
library(tidyverse)
library(ggplot2)
```

```{r load-data, message=FALSE}
plastic_waste <- read.csv(here::here("data/plastic-waste.csv"))
```

## Exercises

```{r}
ggplot(data = plastic_waste) +
  aes(x = plastic_waste_per_cap) +
  geom_histogram(binwidth = 0.2)
#> Warning: Removed 51 rows containing non-finite values (stat_bin).

plastic_waste |>
  filter(plastic_waste_per_cap > 3.5)
#> # A tibble: 1 × 10
#>   code  entity   continent   year gdp_per_cap plastic_waste_p… mismanaged_plast…
#>   <chr> <chr>    <chr>      <dbl>       <dbl>            <dbl>             <dbl>
#> 1 TTO   Trinida… North Ame…  2010      31261.              3.6              0.19
#> # … with 3 more variables: mismanaged_plastic_waste <dbl>, coastal_pop <dbl>,
#> #   total_pop <dbl>
```

### Exercise 1

Using the histogram and density plot, we can see that North America has the highest plastic waste per capita, and Africa has the lowest plastic waste per capita.

```{r plastic-waste-continent}
ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap, color = continent, fill = continent) +
  geom_histogram(binwidth = 1) +
  geom_density(
    aes(y = after_stat(count))
  )

ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap, color = continent, fill = continent) +
  geom_density(alpha = 0.2)

# we define fill and colour in the aesthetics because they are applied based on the dataset, but we define the alpha directly in the geom because it applies generally.
```

### Exercise 2

```{r plastic-waste-density}
ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap,
      y = continent,
      fill = continent) +
  geom_jitter(height = .15,
              alpha = .5) +
  geom_boxplot(color = "black",
               alpha = .5,
               width = .1,
               size = .5) +
  ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .5,
                    position = position_nudge(y = .2))
# the density and data points show the outliers in North America that the boxplot does not display on the graph.

```

### Exercise 3

Remove this text, and add your answer for Exercise 3 here.
```{r}
# 3.1
ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap, y = mismanaged_plastic_waste_per_cap, fill = continent) +
  geom_point()

# As plastic waste per cap increases, mismanaged plastic waste per cap also increases.

# 3.2
ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap, y = mismanaged_plastic_waste_per_cap, color = continent) +
  geom_point()

# 3.3
ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap, y = total_pop, color = continent) +
  geom_line() +
  geom_smooth()

ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap, y = coastal_pop, color = continent) +
  geom_line() +
  geom_smooth()

```

## Pro-Tips

### Excercise 3

Try this :D

```
ggplot(data = plastic_waste, 
       mapping = aes(x = continent, 
                     y = plastic_waste_per_cap)) +
  geom_violin()+
  geom_boxplot(width=.3, fill="green") +
  stat_summary(fun.y=median, geom="point") 
```

### Exercise 5 

Helpful reference:http://www.sthda.com/english/wiki/ggplot2-themes-and-background-colors-the-3-elements



