---
title: "Lab-6-join-those-tables"
author: "Priya Singh Collins"
date: "2/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

#Exercise 1

```{r}
#setup
songs <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/songs.csv")
locations <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/loc.csv")

(time <- as_tibble(songs) |> 
   rename(song = title))

(album <- as_tibble(locations) |> 
   select(title, everything()) |> 
   rename(album = release,
          song  = title))

#1.1
time |> 
  left_join(album, by = c("song", "artist_name"))

#1.2
time |> 
  full_join(album, by = "song", "artist_name")

#1.3
time |> 
  anti_join(album, by = "song")

#1.4
time |> 
  anti_join(album, by = "artist_name")

#1.5
time |> 
  full_join(album, by = "song")

```

#Exercise 2
```{r}
fell <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Fellowship_Of_The_Ring.csv")
ttow <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Two_Towers.csv")
retk <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Return_Of_The_King.csv")
```

```{r}
#2.1
bind_rows(fell, ttow, retk)

#2.2
fell |> 
  anti_join(retk, by = "Race") |> 
  anti_join(ttow, by = "Race")

```

#Exercise 3
```{r}
(y <-  tibble(x1 = LETTERS[1:3], x2 = 1:3))
(z <- tibble(x1 = c("B", "C", "D"), x2 = 2:4))

```

```{r}
#3.1
intersect(y, z)

#3.2
union(
  mutate(y, day = "Day 1"),
  mutate(z, day = "Day 2")
)

#3.3
setdiff(y, z)

```